version: '3.8'

services:
  web:
    build: .
    container_name: stockhome_php
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: stockhome_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongodb_data:
