version: '3.8'

services:
  web:
    build: .
    container_name: web.stockhome.in
    ports:
      - "127.0.0.1:8080:80"  
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mongodb
    networks:
      - stockhome_network

  mongodb:
    image: mongo:latest
    container_name: mongodb.stockhome.in
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - stockhome_network

volumes:
  mongodb_data:

networks:
  stockhome_network:
    driver: bridge
